import type { Assessment, FeatureGrade, ImprovementTip, UserProfile, ProgressEntry } from './types';

export const DEMO_USER: UserProfile = {
  name: 'Alex',
  assessmentCount: 7,
  streakDays: 12,
  joinedDate: '2026-04-10',
  bestFeature: 'Eye Area',
  focusArea: 'Jawline',
};

const FEATURES: FeatureGrade[] = [
  {
    id: 'jawline',
    name: 'Jawline',
    grade: 'C+',
    score: 58,
    description: 'Moderate jawline definition. Slight excess submental fat reducing sharpness. Mandibular angle could be more pronounced.',
    icon: 'jawline',
    tips: [
      'Practice mewing — tongue posture on the palate 24/7',
      'Chew mastic gum 30 min/day for masseter hypertrophy',
      'Reduce sodium to minimize water retention',
      'Lose body fat to 12-15% for visible jaw definition',
      'Consider jawline exercises (chin tucks, neck curls)',
    ],
    category: 'structure',
  },
  {
    id: 'eye-area',
    name: 'Eye Area',
    grade: 'B+',
    score: 82,
    description: 'Good eye shape with positive canthal tilt. Minimal upper eyelid exposure. Slight dark circles from lack of sleep.',
    icon: 'eye',
    tips: [
      'Get 7-9 hours of quality sleep consistently',
      'Apply caffeine eye cream morning and night',
      'Use cold compress for 5 min to reduce puffiness',
      'Stay hydrated — 3L water minimum daily',
      'Wear blue-light glasses if you screen-time heavily',
    ],
    category: 'features',
  },
  {
    id: 'skin-texture',
    name: 'Skin Texture',
    grade: 'B-',
    score: 70,
    description: 'Generally clear skin with minor textural inconsistencies. Some visible pores on nose and cheeks. Light hyperpigmentation.',
    icon: 'skin',
    tips: [
      'Use retinol 0.5% every other night (build tolerance)',
      'Apply SPF 50 every morning — non-negotiable',
      'Double cleanse PM: oil cleanser → gentle foaming',
      'Niacinamide 10% serum for pore refinement',
      'Chemical exfoliant (AHA/BHA) 2x per week',
    ],
    category: 'skin',
  },
  {
    id: 'symmetry',
    name: 'Facial Symmetry',
    grade: 'B',
    score: 76,
    description: 'Above-average facial symmetry. Minor asymmetry in brow position and slight deviation in nasal bridge. Not noticeable in conversation.',
    icon: 'symmetry',
    tips: [
      'Sleep on your back to prevent facial compression',
      'Chew evenly on both sides of your mouth',
      'Correct posture — forward head posture causes asymmetry',
      'Consider facial massage to relax overactive muscles',
    ],
    category: 'structure',
  },
  {
    id: 'hair',
    name: 'Hair Quality',
    grade: 'A-',
    score: 86,
    description: 'Strong hairline with good density. Healthy hair texture and shine. Norwood 1 classification — no recession.',
    icon: 'hair',
    tips: [
      'Use ketoconazole shampoo 2x/week as prevention',
      'Take biotin + zinc daily for hair strength',
      'Minimize heat styling — air dry when possible',
      'Get a fresh cut every 3-4 weeks for clean look',
    ],
    category: 'features',
  },
  {
    id: 'lips',
    name: 'Lip Ratio',
    grade: 'B',
    score: 74,
    description: 'Balanced lip proportions with adequate vermillion show. Upper-to-lower lip ratio within aesthetic range. Slight dryness.',
    icon: 'lips',
    tips: [
      'Exfoliate lips weekly with sugar scrub',
      'Apply lip balm with SPF during the day',
      'Stay hydrated for natural plumpness',
      'Use hyaluronic acid lip treatment at night',
    ],
    category: 'features',
  },
  {
    id: 'skin-clarity',
    name: 'Skin Clarity',
    grade: 'C',
    score: 55,
    description: 'Some active breakouts on chin and forehead. Post-inflammatory hyperpigmentation from past acne. T-zone oiliness.',
    icon: 'clarity',
    tips: [
      'Use benzoyl peroxide 2.5% as spot treatment',
      'Salicylic acid cleanser for T-zone control',
      'Change pillowcase every 2-3 days',
      'Cut dairy and refined sugar for 30 days',
      'Don\'t touch your face — bacteria transfer causes breakouts',
      'Consider azelaic acid 15% for hyperpigmentation',
    ],
    category: 'skin',
  },
  {
    id: 'brow-ridge',
    name: 'Brow Ridge',
    grade: 'B-',
    score: 68,
    description: 'Moderate brow ridge projection. Decent brow shape but could benefit from slight grooming. Good brow-to-eye ratio.',
    icon: 'brow',
    tips: [
      'Get brows professionally shaped — clean up strays',
      'Use castor oil nightly for thicker brow growth',
      'Don\'t over-pluck — masculine brows are fuller',
      'Consider brow lamination for a structured look',
    ],
    category: 'features',
  },
];

export const DEMO_ASSESSMENT: Assessment = {
  id: 'assessment-1',
  date: '2026-05-24',
  overallGrade: 'B-',
  overallScore: 71,
  features: FEATURES,
};

export const PAST_ASSESSMENTS: Assessment[] = [
  {
    id: 'assessment-old-6',
    date: '2026-03-15',
    overallGrade: 'C',
    overallScore: 55,
    features: FEATURES.map(f => ({ ...f, score: Math.max(20, f.score - 22), grade: 'C' as const })),
  },
  {
    id: 'assessment-old-5',
    date: '2026-03-29',
    overallGrade: 'C+',
    overallScore: 59,
    features: FEATURES.map(f => ({ ...f, score: Math.max(25, f.score - 18), grade: 'C+' as const })),
  },
  {
    id: 'assessment-old-4',
    date: '2026-04-05',
    overallGrade: 'C+',
    overallScore: 62,
    features: FEATURES.map(f => ({ ...f, score: Math.max(30, f.score - 14), grade: 'C+' as const })),
  },
  {
    id: 'assessment-old-3',
    date: '2026-04-15',
    overallGrade: 'B-',
    overallScore: 65,
    features: FEATURES.map(f => ({ ...f, score: Math.max(35, f.score - 10), grade: 'B-' as const })),
  },
  {
    id: 'assessment-old-2',
    date: '2026-05-01',
    overallGrade: 'B-',
    overallScore: 68,
    features: FEATURES.map(f => ({ ...f, score: Math.max(40, f.score - 5), grade: 'B-' as const })),
  },
  {
    id: 'assessment-old-1',
    date: '2026-05-14',
    overallGrade: 'B-',
    overallScore: 70,
    features: FEATURES.map(f => ({ ...f, score: Math.max(42, f.score - 2), grade: 'B-' as const })),
  },
  { ...DEMO_ASSESSMENT },
];

export const PROGRESS_DATA: ProgressEntry[] = [
  { date: 'Mar 15', score: 55 },
  { date: 'Mar 29', score: 59 },
  { date: 'Apr 5', score: 62 },
  { date: 'Apr 15', score: 65 },
  { date: 'May 1', score: 68 },
  { date: 'May 14', score: 70 },
  { date: 'May 24', score: 71 },
];

export const IMPROVEMENT_TIPS: ImprovementTip[] = [
  {
    id: 'tip-1',
    featureId: 'jawline',
    title: 'Mewing Practice',
    description: 'Keep your tongue pressed against the roof of your mouth at all times. This proper oral posture can improve jawline definition over months.',
    difficulty: 'easy',
    timeframe: '3-6 months',
    category: 'exercise',
  },
  {
    id: 'tip-2',
    featureId: 'jawline',
    title: 'Mastic Gum Chewing',
    description: 'Chew hard mastic gum for 30 minutes daily to build masseter muscle mass, creating a wider and more defined jaw.',
    difficulty: 'easy',
    timeframe: '2-4 months',
    category: 'exercise',
  },
  {
    id: 'tip-3',
    featureId: 'skin-clarity',
    title: 'Retinol Night Routine',
    description: 'Start with retinol 0.25% twice a week, gradually increasing to 0.5% every other night. Best anti-aging and skin-clearing ingredient.',
    difficulty: 'medium',
    timeframe: '6-12 weeks',
    category: 'skincare',
  },
  {
    id: 'tip-4',
    featureId: 'skin-clarity',
    title: 'Cut Dairy Challenge',
    description: 'Eliminate dairy for 30 days. Dairy raises IGF-1 which triggers excess sebum production and hormonal acne.',
    difficulty: 'hard',
    timeframe: '30 days',
    category: 'nutrition',
  },
  {
    id: 'tip-5',
    featureId: 'eye-area',
    title: 'Sleep Optimization',
    description: 'Get 7-9 hours of quality sleep. Use blackout curtains, keep room at 65°F, no screens 1hr before bed.',
    difficulty: 'medium',
    timeframe: '1-2 weeks',
    category: 'lifestyle',
  },
  {
    id: 'tip-6',
    featureId: 'skin-texture',
    title: 'Daily SPF Protection',
    description: 'Apply SPF 50 every morning, even on cloudy days. UV damage is the #1 cause of premature aging and skin texture issues.',
    difficulty: 'easy',
    timeframe: 'Ongoing',
    category: 'skincare',
  },
  {
    id: 'tip-7',
    featureId: 'hair',
    title: 'Finasteride Prevention',
    description: 'Consult a dermatologist about low-dose finasteride if you notice any recession. Prevention is 10x easier than restoration.',
    difficulty: 'medium',
    timeframe: 'Ongoing',
    category: 'lifestyle',
  },
  {
    id: 'tip-8',
    featureId: 'jawline',
    title: 'Body Fat Reduction',
    description: 'Get to 12-15% body fat through caloric deficit and resistance training. Face fat is one of the last areas to lean out.',
    difficulty: 'hard',
    timeframe: '3-6 months',
    category: 'nutrition',
  },
  {
    id: 'tip-9',
    featureId: 'symmetry',
    title: 'Back Sleeping',
    description: 'Train yourself to sleep on your back. Side sleeping compresses one side of your face for hours, worsening asymmetry.',
    difficulty: 'medium',
    timeframe: '2-4 weeks',
    category: 'lifestyle',
  },
  {
    id: 'tip-10',
    featureId: 'brow-ridge',
    title: 'Professional Brow Shaping',
    description: 'Get your eyebrows professionally shaped once, then maintain at home. Clean brows frame the face and enhance perceived masculinity.',
    difficulty: 'easy',
    timeframe: '1 session',
    category: 'grooming',
  },
];
