import type { Assessment, FeatureGrade, ImprovementTip, UserProfile, ProgressEntry } from './types';

export const DEMO_USER: UserProfile = {
  name: 'Alex',
  assessmentCount: 7,
  streakDays: 12,
  joinedDate: '2026-04-10',
  bestFeature: 'Hunter Eyes Composite',
  focusArea: 'Jawline & Gonial Angle',
};

const FEATURES: FeatureGrade[] = [
  {
    id: 'canthal-tilt',
    name: 'Canthal Tilt',
    grade: 'B',
    score: 72,
    description: 'Slight positive tilt, approximately +2° estimated',
    icon: 'eye',
    tips: [
      'Positive canthal tilt is primarily genetic — limited natural interventions',
      'Ensure good under-eye care (sleep, hydration) to prevent drooping appearance',
      'Maintain low body fat to avoid orbital fat pad sagging',
      'Consider blepharoplasty consultation if severe negative tilt (surgical only)',
    ],
    category: 'miscellaneous',
    idealRange: '+3° to +7°',
  },
  {
    id: 'hunter-eyes',
    name: 'Hunter Eyes Composite',
    grade: 'B+',
    score: 84,
    description: 'Good hooding and depth, strong limbal ring, well-set orbital structure',
    icon: 'eye',
    tips: [
      'Get 7-9 hours of sleep to maximize limbal ring contrast',
      'Use cold compresses to reduce orbital puffiness',
      'Maintain low body fat — orbital fat pads diminish eye depth',
      'Stay hydrated — dehydration reduces limbal ring visibility',
      'Wear blue-light glasses to prevent eye strain and redness',
    ],
    category: 'dimorphism',
    idealRange: 'Deep-set, hooded, strong limbal ring',
  },
  {
    id: 'symmetry',
    name: 'Facial Symmetry',
    grade: 'A-',
    score: 88,
    description: 'High bilateral match, 96% symmetry estimated, minimal asymmetry',
    icon: 'symmetry',
    tips: [
      'Sleep on your back to prevent facial compression asymmetry',
      'Chew evenly on both sides to balance masseter development',
      'Correct forward head posture — asymmetry often postural',
      'Consider facial massage to relax overactive unilateral muscles',
    ],
    category: 'harmony',
    idealRange: '95–99% bilateral match',
  },
  {
    id: 'facial-thirds',
    name: 'Facial Thirds & Harmony',
    grade: 'B-',
    score: 76,
    description: 'Slightly long upper third (35/32/33), good overall balance',
    icon: 'ruler',
    tips: [
      'Optimize hairstyle to balance upper third (fringe can shorten forehead visually)',
      'Facial harmony is primarily structural — limited non-surgical options',
      'Maintain lean body fat to reveal true facial proportions',
      'Consider beard styling to adjust lower-third perception',
    ],
    category: 'harmony',
    idealRange: '33/33/33 (hairline-to-brow / brow-to-nose base / nose base-to-chin)',
  },
  {
    id: 'fwhr',
    name: 'FWHR',
    grade: 'B+',
    score: 85,
    description: '1.9 FWHR, ideal masculine width-to-height ratio',
    icon: 'scan',
    tips: [
      'Chew mastic gum to widen masseter muscles (increases bizygomatic width)',
      'Lose body fat to reveal true bone structure',
      'Facial width is primarily genetic — limited natural changes',
      'Hairstyle can visually adjust perceived width (side volume vs. top height)',
    ],
    category: 'harmony',
    idealRange: '1.85–2.0 (men) / 1.6–1.75 (women)',
  },
  {
    id: 'jawline-gonial',
    name: 'Jawline & Gonial Angle',
    grade: 'C+',
    score: 68,
    description: '115° gonial angle, good definition but slight softness at mandibular border',
    icon: 'jawline',
    tips: [
      'Practice mewing — tongue posture on the palate 24/7 for forward growth',
      'Chew mastic gum 30 min/day for masseter hypertrophy',
      'Reduce sodium to minimize water retention masking definition',
      'Lose body fat to 12-15% for visible jaw definition',
      'Consider jawline exercises (chin tucks, neck curls) with caution',
    ],
    category: 'dimorphism',
    idealRange: '110–120° (men) / 120–128° (women)',
  },
  {
    id: 'chin-projection',
    name: 'Chin Projection',
    grade: 'B',
    score: 82,
    description: 'Adequate projection, chin aligned with lower lip in Frankfurt horizontal',
    icon: 'jawline',
    tips: [
      'Chin projection is primarily skeletal — limited non-surgical options',
      'Maintain proper tongue posture (mewing) to support forward growth in youth',
      'Lose facial fat to reveal true chin projection',
      'Beard styling can visually adjust weak chin (goatee extends perceived projection)',
    ],
    category: 'dimorphism',
    idealRange: 'Chin equal to or slightly behind lower lip in Frankfurt horizontal',
  },
  {
    id: 'cheekbone-ogee',
    name: 'Cheekbone Projection & Ogee Curve',
    grade: 'B',
    score: 79,
    description: 'Moderate cheekbone projection, visible ogee curve present but not prominent',
    icon: 'scan',
    tips: [
      'Lose body fat to 10-12% to reveal underlying cheekbone structure',
      'Chewing exercises may slightly enhance zygomatic arch prominence',
      'Avoid excessive sodium — water retention masks cheekbone definition',
      'Cheekbone height/projection is primarily genetic',
    ],
    category: 'angularity',
    idealRange: 'Cheekbones projecting forward of mid-face with visible S-curve',
  },
  {
    id: 'eye-bags',
    name: 'Eye Bags & Under-Eye',
    grade: 'C-',
    score: 64,
    description: 'Mild under-eye puffiness, slight dark circles from insufficient sleep',
    icon: 'eye',
    tips: [
      'Get 7-9 hours of quality sleep consistently',
      'Apply caffeine eye cream morning and night',
      'Use cold compress for 5 min to reduce puffiness',
      'Stay hydrated — 3L water minimum daily',
      'Reduce sodium intake to prevent fluid retention',
      'Consider vitamin K cream for dark circles',
    ],
    category: 'miscellaneous',
    idealRange: 'Smooth flat infraorbital, no festoons or dark hollowing',
  },
  {
    id: 'skin-texture',
    name: 'Skin Quality & Texture',
    grade: 'C+',
    score: 71,
    description: 'Some visible pores on T-zone, minor textural inconsistencies, generally clear',
    icon: 'skin',
    tips: [
      'Use retinol 0.5% every other night (build tolerance slowly)',
      'Apply SPF 50 every morning — non-negotiable',
      'Double cleanse PM: oil cleanser → gentle foaming cleanser',
      'Niacinamide 10% serum for pore refinement',
      'Chemical exfoliant (AHA/BHA) 2x per week maximum',
      'Stay hydrated and get adequate sleep for skin repair',
    ],
    category: 'miscellaneous',
    idealRange: 'Smooth even texture, zero active inflammation',
  },
  {
    id: 'skin-clarity',
    name: 'Skin Clarity',
    grade: 'D+',
    score: 58,
    description: 'Active breakouts on chin, post-acne hyperpigmentation, T-zone oiliness',
    icon: 'clarity',
    tips: [
      'Use benzoyl peroxide 2.5% as spot treatment for active acne',
      'Salicylic acid cleanser for T-zone control and pore clearing',
      'Change pillowcase every 2-3 days to prevent bacteria transfer',
      'Cut dairy and refined sugar for 30 days (reduces IGF-1)',
      "Don't touch your face — bacteria transfer causes breakouts",
      'Consider azelaic acid 15% for hyperpigmentation and redness',
    ],
    category: 'miscellaneous',
    idealRange: 'Even tone, no hyperpigmentation or post-acne marks',
  },
  {
    id: 'philtrum-lip',
    name: 'Philtrum & Lip Ratio',
    grade: 'B-',
    score: 75,
    description: '14 mm philtrum (ideal range), balanced upper-to-lower lip ratio ~1:1.6',
    icon: 'lips',
    tips: [
      'Philtrum length is skeletal — no natural shortening methods',
      'Exfoliate lips weekly with sugar scrub for smooth texture',
      'Apply lip balm with SPF during the day to prevent darkening',
      'Stay hydrated for natural lip plumpness',
      'Use hyaluronic acid lip treatment at night',
    ],
    category: 'miscellaneous',
    idealRange: 'Philtrum 13–15 mm (men) / 11–13 mm (women), lip ratio ~1:1.6',
  },
];

export const DEMO_ASSESSMENT: Assessment = {
  id: 'assessment-1',
  date: '2026-05-24',
  overallGrade: 'B-',
  overallScore: 75,
  pslTier: 'HTN',
  features: FEATURES,
};

export const PAST_ASSESSMENTS: Assessment[] = [
  {
    id: 'assessment-old-6',
    date: '2026-03-15',
    overallGrade: 'C',
    overallScore: 58,
    pslTier: 'LTN',
    features: FEATURES.map(f => ({ ...f, score: Math.max(35, f.score - 22), grade: 'C' as const })),
  },
  {
    id: 'assessment-old-5',
    date: '2026-03-29',
    overallGrade: 'C+',
    overallScore: 62,
    pslTier: 'LTN',
    features: FEATURES.map(f => ({ ...f, score: Math.max(40, f.score - 18), grade: 'C+' as const })),
  },
  {
    id: 'assessment-old-4',
    date: '2026-04-05',
    overallGrade: 'C+',
    overallScore: 65,
    pslTier: 'MTN',
    features: FEATURES.map(f => ({ ...f, score: Math.max(45, f.score - 14), grade: 'C+' as const })),
  },
  {
    id: 'assessment-old-3',
    date: '2026-04-15',
    overallGrade: 'B-',
    overallScore: 68,
    pslTier: 'MTN',
    features: FEATURES.map(f => ({ ...f, score: Math.max(48, f.score - 10), grade: 'B-' as const })),
  },
  {
    id: 'assessment-old-2',
    date: '2026-05-01',
    overallGrade: 'B-',
    overallScore: 71,
    pslTier: 'HTN',
    features: FEATURES.map(f => ({ ...f, score: Math.max(51, f.score - 5), grade: 'B-' as const })),
  },
  {
    id: 'assessment-old-1',
    date: '2026-05-14',
    overallGrade: 'B-',
    overallScore: 73,
    pslTier: 'HTN',
    features: FEATURES.map(f => ({ ...f, score: Math.max(53, f.score - 2), grade: 'B-' as const })),
  },
  { ...DEMO_ASSESSMENT },
];

export const PROGRESS_DATA: ProgressEntry[] = [
  { date: 'Mar 15', score: 58 },
  { date: 'Mar 29', score: 62 },
  { date: 'Apr 5', score: 65 },
  { date: 'Apr 15', score: 68 },
  { date: 'May 1', score: 71 },
  { date: 'May 14', score: 73 },
  { date: 'May 24', score: 75 },
];

export const IMPROVEMENT_TIPS: ImprovementTip[] = [
  {
    id: 'tip-1',
    featureId: 'jawline-gonial',
    title: 'Mewing Practice',
    description: 'Keep your tongue pressed against the roof of your mouth at all times. This proper oral posture can improve jawline definition over months.',
    difficulty: 'easy',
    timeframe: '3-6 months',
    category: 'exercise',
  },
  {
    id: 'tip-2',
    featureId: 'jawline-gonial',
    title: 'Mastic Gum Chewing',
    description: 'Chew hard mastic gum for 30 minutes daily to build masseter muscle mass, creating a wider and more defined jaw.',
    difficulty: 'easy',
    timeframe: '2-4 months',
    category: 'exercise',
  },
  {
    id: 'tip-3',
    featureId: 'skin-clarity',
    title: 'Retinol Night Routine',
    description: 'Start with retinol 0.25% twice a week, gradually increasing to 0.5% every other night. Best anti-aging and skin-clearing ingredient.',
    difficulty: 'medium',
    timeframe: '6-12 weeks',
    category: 'skincare',
  },
  {
    id: 'tip-4',
    featureId: 'skin-clarity',
    title: 'Cut Dairy Challenge',
    description: 'Eliminate dairy for 30 days. Dairy raises IGF-1 which triggers excess sebum production and hormonal acne.',
    difficulty: 'hard',
    timeframe: '30 days',
    category: 'nutrition',
  },
  {
    id: 'tip-5',
    featureId: 'eye-bags',
    title: 'Sleep Optimization',
    description: 'Get 7-9 hours of quality sleep. Use blackout curtains, keep room at 65°F, no screens 1hr before bed.',
    difficulty: 'medium',
    timeframe: '1-2 weeks',
    category: 'lifestyle',
  },
  {
    id: 'tip-6',
    featureId: 'skin-texture',
    title: 'Daily SPF Protection',
    description: 'Apply SPF 50 every morning, even on cloudy days. UV damage is the #1 cause of premature aging and skin texture issues.',
    difficulty: 'easy',
    timeframe: 'Ongoing',
    category: 'skincare',
  },
  {
    id: 'tip-7',
    featureId: 'hunter-eyes',
    title: 'Eye Area Maintenance',
    description: 'Use cold compresses and caffeine eye cream daily. Stay hydrated to maintain limbal ring contrast and reduce puffiness.',
    difficulty: 'easy',
    timeframe: 'Ongoing',
    category: 'skincare',
  },
  {
    id: 'tip-8',
    featureId: 'jawline-gonial',
    title: 'Body Fat Reduction',
    description: 'Get to 12-15% body fat through caloric deficit and resistance training. Face fat is one of the last areas to lean out.',
    difficulty: 'hard',
    timeframe: '3-6 months',
    category: 'nutrition',
  },
  {
    id: 'tip-9',
    featureId: 'symmetry',
    title: 'Back Sleeping',
    description: 'Train yourself to sleep on your back. Side sleeping compresses one side of your face for hours, worsening asymmetry.',
    difficulty: 'medium',
    timeframe: '2-4 weeks',
    category: 'lifestyle',
  },
  {
    id: 'tip-10',
    featureId: 'cheekbone-ogee',
    title: 'Cheekbone Definition',
    description: 'Lose body fat to 10-12% to reveal underlying cheekbone structure. Avoid excessive sodium to prevent masking.',
    difficulty: 'hard',
    timeframe: '3-6 months',
    category: 'nutrition',
  },
];
